# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PythonPackage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Sort imports with isort
        run: |
          isort **/*.py
      - name: Format code with black
        run: |
          black jsonschema2dj
      - name: Lint with flake8
        run: |
          flake8 jsonschema_tools
      - name: Test with pytest
        run: |
          pytest --cov=jsonschema2dj --cov-report=term-missing -cov-fail-under=88
#      - name: Test with doctest
#        run: |
#          pytest --doctest-modules jsonschema2dj
      - name: Static typechecking with mypy
        run: |
          mypy .
